
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Jul 09 20:53:24 CST 2014
//----------------------------------------------------

package proyecto.compilador.lenguaje;

/** CUP generated class containing symbol constants. */
public class SymLenguaje {
  /* terminals */
  public static final int continueS = 56;
  public static final int orS = 34;
  public static final int ampersand = 36;
  public static final int corcheteI = 19;
  public static final int funLienzo = 52;
  public static final int numDecimal = 5;
  public static final int array = 16;
  public static final int dosPuntos = 32;
  public static final int corcheteD = 20;
  public static final int coma = 10;
  public static final int igual = 9;
  public static final int funOvalo = 50;
  public static final int pareI = 17;
  public static final int ambito = 42;
  public static final int pareD = 18;
  public static final int opComparacion = 6;
  public static final int caracter = 54;
  public static final int funImprimir = 53;
  public static final int switchS = 30;
  public static final int doS = 21;
  public static final int numEntero = 4;
  public static final int thisS = 44;
  public static final int importar = 45;
  public static final int clase = 41;
  public static final int tipoDato = 3;
  public static final int menos = 12;
  public static final int EOF = 0;
  public static final int mas = 11;
  public static final int funArco = 48;
  public static final int igualOperador = 38;
  public static final int error = 1;
  public static final int elseS = 27;
  public static final int notS = 37;
  public static final int andS = 35;
  public static final int caseS = 31;
  public static final int funTexto = 47;
  public static final int funPoligono = 51;
  public static final int llaveI = 28;
  public static final int extendsS = 43;
  public static final int punto = 39;
  public static final int funLinea = 46;
  public static final int llaveD = 29;
  public static final int id = 57;
  public static final int ifS = 26;
  public static final int incremento = 7;
  public static final int valBool = 2;
  public static final int whileS = 22;
  public static final int returnS = 40;
  public static final int multi = 13;
  public static final int newS = 24;
  public static final int decremento = 8;
  public static final int breakS = 25;
  public static final int expo = 15;
  public static final int div = 14;
  public static final int forS = 23;
  public static final int funRectangulo = 49;
  public static final int interrogacion = 33;
  public static final int cadena = 55;
}

