
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Aprkkkkkk 23 05:20:34 CST 2016
//----------------------------------------------------

package proyecto.interprete3d;

/** CUP generated class containing symbol constants. */
public class Sym3D {
  /* terminals */
  public static final int ifS = 17;
  public static final int cadena = 20;
  public static final int corcheteD = 10;
  public static final int coma = 11;
  public static final int temporal = 2;
  public static final int returnS = 18;
  public static final int numero = 4;
  public static final int opMat = 14;
  public static final int llaveI = 7;
  public static final int llaveD = 8;
  public static final int igual = 16;
  public static final int EOF = 0;
  public static final int id = 21;
  public static final int opRel = 15;
  public static final int parentesisI = 5;
  public static final int error = 1;
  public static final int etiqueta = 3;
  public static final int parentesisD = 6;
  public static final int call = 22;
  public static final int dosPuntos = 13;
  public static final int puntoComa = 12;
  public static final int printf = 19;
  public static final int corcheteI = 9;
}

