
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Jul 04 21:21:38 CST 2014
//----------------------------------------------------

package proyecto.compilador.proyectos;

/** CUP generated class containing symbol constants. */
public class SymProyectos {
  /* terminals */
  public static final int ruta = 12;
  public static final int diagonal = 6;
  public static final int proyecto = 7;
  public static final int cadena = 2;
  public static final int archivos = 9;
  public static final int EOF = 0;
  public static final int menor = 3;
  public static final int principal = 8;
  public static final int error = 1;
  public static final int archivo = 10;
  public static final int nombre = 11;
  public static final int mayor = 4;
  public static final int igual = 5;
}

